# Generated by Django 5.0.14 on 2025-08-14 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='updaed',
            new_name='updated',
        ),
    ]
