# Generated by Django 5.0.14 on 2025-08-17 08:03

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_updaed_post_updated'),
    ]

    operations = [
        TrigramExtension()
    ]
